# Sample Use: ansible-playbook -i hosts destroy-vm.yml -e vm_name=ProjectGuestVM5
- name: Terminates the VM from the host
  hosts: localhost
  become: yes

  tasks:
    - debug: msg="{{vm_name}}"

    - name: Check if VM exists
      shell: virsh list --all | grep {{vm_name}}
      register: vm_exists
      ignore_errors: true

    - name: Shut down the VM
      virt:
        name: "{{ vm_name }}"
        state: destroyed
      become: yes
      when: vm_exists.rc == 0
      
    - name: Undefining the VM
      shell: "virsh undefine {{ vm_name }} --remove-all-storage"
      become: yes
      when: vm_exists.rc == 0

    - name: Cleaning up the pending images directories on the host
      command: "rm -rf /var/lib/libvirt/images/{{ vm_name }}"
      become: yes
