vms:
- vm_name: RVM_T1_T1-V1
  vcpu: 2
  mem: 2048
  disk_size: 10G
  interfaces:
  - network_name: host-nat-network
    iface_name: enp1s0
    ipaddress: 172.16.0.2/12
    dhcp: false
    gateway: 172.16.0.1
  - network_name: T1-V1-S1
    iface_name: enp2s0
    ipaddress: 192.168.10.1/24
    dhcp: false
  - network_name: T1-V1-S2
    iface_name: enp3s0
    ipaddress: 192.168.20.1/24
    dhcp: false
  - network_name: host-public-network
    iface_name: enp4s0
    ipaddress: 10.10.10.2/24
    tenantIps: {}
