vms:
- vm_name: RVM_A_A-A
  vcpu: 2
  mem: 2048
  disk_size: 10G
  interfaces:
  - network_name: host-nat-network
    iface_name: enp1s0
    ipaddress: 172.16.0.2/12
    dhcp: false
    gateway: 172.16.0.1
