vms:
  - vm_name: VM1
    vcpu: 2
    mem: 2048
    disk_size: 12G
    interfaces: 
      - network_name: "C1S1"
        iface_name: enp1s0
        dhcp: false
        ipaddress: 10.1.1.4/24
        gateway: 10.1.1.2
        nameserver: 8.8.8.8
 
    