---
- name: Create LB rules
  hosts: all
  become: yes
  vars_files:
    - vars/lb-vars.yml
    
  tasks:
    - name: generate lbaas rules
      template:
        src: lbaas_rules.j2
        dest: "{{ playbook_dir }}/{{ container_name }}_rules.sh"
      when: lb_snat_ip is defined
      become: yes
    
    - name: generate Iaas LB rules
      template:
        src: iaas_lb_rules.j2
        dest: "{{ playbook_dir }}/{{ container_name }}_rules.sh"
      when: lb_snat_ip is not defined
      become: yes
    
    - name: add rules to the LB container
      command: "ip netns exec {{ container_name }} bash {{ playbook_dir }}/{{ container_name }}_rules.sh"
      become: yes