---
- name: Create containers
  hosts: all
  become: yes
  vars_files:
    - vars/container-vars.yml

  tasks:
    #create vpc container
    - name: Create VPC/LoadBalancer Container
      command: "docker run -d --name {{ container_name }} -h {{ container_name }} --network none {{ container_image }}"
      become: yes
      when: vcpu is not defined and mem is not defined

    - name: Create VM Container
      command: "docker run -d --name {{ container_name }} -h {{ container_name }} -m {{ mem }} --cpus {{ vcpu }} --network none {{ container_image }}"
      become: yes
      when: vcpu is defined and mem is defined

    #link namespace
    - name: Execute docker to namespace
      script: docker_to_netnsh.sh {{ container_name }}
      args:
        executable: /bin/bash
      become: yes